// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './fresh.config.ts';

// NOTE: Routes and Islands are not yet implemented.
// When implementing, add routes in deno/routes/ and islands in deno/islands/
// and regenerate this file with `deno run -A https://deno.land/x/fresh/init.ts .`

const manifest = {
  routes: {
    // Add routes here when implemented:
    // './routes/index.tsx': () => import('./routes/index.tsx'),
    // './routes/api/webmention.ts': () => import('./routes/api/webmention.ts'),
  },
  islands: {
    // Add islands here when implemented:
    // './islands/SemanticGraph.tsx': () => import('./islands/SemanticGraph.tsx'),
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
